<?php 
    echo "Welcome to php<br>";
    print "Welcome to php";
    echo "<br>";
    $str = "I learn PHP PHP aaaaaa";
    $str1 = "I learn html";
    print_r(str_getcsv($str, ","));
    echo "<br>";
    echo str_pad($str,50,"*",STR_PAD_LEFT);
    echo "<br>";
    echo str_ireplace("PHP", "HTML", $str);
    echo "<br>";
    echo str_replace("php","html",$str);
    echo "<br>";
    echo str_repeat($str,3);
    echo "<br>";
    echo str_rot13($str);
    echo "<br>";
    echo str_shuffle($str);
    echo "<br>";
    $arr=  str_split($str, 3);
    print_r($arr);
    echo "<br>";
    echo str_word_count($str);
    echo "<br>";
    echo strcasecmp($str1,$str);
    echo "<br>";
    echo strchr($str, "e");
    echo "<br>";
    echo strcmp($str, $str1);
    echo "<br>";
    echo strcoll($str1,$str);
    echo "<br>";
    echo strcspn($str, "a",1, 8);
    echo "<br>";
    echo stripcslashes("APPLES's \ phone");
    echo "<br>";
    echo stripslashes("APPLES's \ phone");
    echo "<br>";
    echo stripos($str, "L");
    echo "<br>";
    echo strpos($str,"l");
    echo "<br>";
    var_dump(strpos($str, "L"));
    echo "<br>";
    echo stristr($str, "p");
    echo "<br>";
    var_dump(strstr($str,"p"));
    echo "<br>";
    echo strlen($str);
    echo "<br>";
    echo strnatcasecmp($str,$str1);
    echo "<br>";
    echo strnatcmp($str, $str1);
    echo "<br>";
    echo strncasecmp($str,$str1,6);
    echo "<br>";
    echo strncmp($str,$str1,3);
    echo "<br>";
    echo strpbrk($str,"abl");
    echo "<br>";
    var_dump(strrchr($str,"h"));
    echo "<br>";
    echo strrchr($str,"H");
    echo "<br>";
    echo strripos($str,"P");
    echo "<br>";
    var_dump(strrpos($str,"p"));
    echo "<br>";
    echo strrpos($str,"P");
    echo "<br>";
    echo strspn($str, "learn",1,19);
    echo "<br>";
    echo substr($str,2,16);
    echo "<br>";
    echo substr("Hello world",6,6)."<br>";
    echo "<br>";
    echo substr("Hello world",-10,-2)."<br>"; //negative
    echo "<br>";
    echo substr_compare($str1,$str,1,19);
    echo "<br>";
    echo substr_count($str, "P");
    echo "<br>";
    echo substr_replace($str, ".....", 3,5);
    echo "<br>";
    echo strstr($str,"P");


?>
